version: '3.4'

services:
  
  redis:
    image: redis:alpine

  masa.auth.database:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
       - "1433:1433"
     environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y

  masa.auth.web.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - masa.auth.service.admin

  masa.auth.service.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  masa.auth.service.admin.dapr:
    image: "daprio/daprd:1.5.1"
    command: ["./daprd",
      "-app-id", "masa-auth-service-admin",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    depends_on:
      - masa.auth.service.admin
    volumes:
      - "./dapr/components/:/components"
    network_mode: "service:masa.auth.service.admin"


  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"